// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFHi0niYrFmdqwPVKKb-nb91vVUsQK1-w',
    appId: '1:983863766103:web:5182c300ec0d2d0ec94712',
    messagingSenderId: '983863766103',
    projectId: 'finalproject-c944b',
    authDomain: 'finalproject-c944b.firebaseapp.com',
    storageBucket: 'finalproject-c944b.firebasestorage.app',
    measurementId: 'G-T32HSQXNG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdM5f2DqMWvV8ogA7JCdUuH5HMTkgDDAY',
    appId: '1:983863766103:android:f10fd0f410d7a832c94712',
    messagingSenderId: '983863766103',
    projectId: 'finalproject-c944b',
    storageBucket: 'finalproject-c944b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqd2sShOs9Fyap79-BSZttAJ1z-XI0QPA',
    appId: '1:983863766103:ios:63003db2173a6f9cc94712',
    messagingSenderId: '983863766103',
    projectId: 'finalproject-c944b',
    storageBucket: 'finalproject-c944b.firebasestorage.app',
    iosBundleId: 'com.example.madFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqd2sShOs9Fyap79-BSZttAJ1z-XI0QPA',
    appId: '1:983863766103:ios:63003db2173a6f9cc94712',
    messagingSenderId: '983863766103',
    projectId: 'finalproject-c944b',
    storageBucket: 'finalproject-c944b.firebasestorage.app',
    iosBundleId: 'com.example.madFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFHi0niYrFmdqwPVKKb-nb91vVUsQK1-w',
    appId: '1:983863766103:web:590c5172e43eddb6c94712',
    messagingSenderId: '983863766103',
    projectId: 'finalproject-c944b',
    authDomain: 'finalproject-c944b.firebaseapp.com',
    storageBucket: 'finalproject-c944b.firebasestorage.app',
    measurementId: 'G-4W6W5N29KL',
  );
}
